version: "3.9"
services:
  book-library:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URL
      - PORT
      - CLOUDINARY_CLOUD_NAME
      - CLOUDINARY_API_KEY
      - CLOUDINARY_API_SECRET
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"